### ISSUE TITLE
traits episode to-do

### ISSUE THREAD

**Issue by connor-french** [role-model/multidim-biodiv-data#28]
To-do before our trial run:
- [x] Update questions to be more informative
- [x] change data path for traits and abundance
- [x] remove the knitr::kable() chunks
- [x] left_join: "sticking two things together with a shared column"
- [x] write over names if it would normally be done with a pipe
- [x] Rearrange visualization to come before the summary stats/integrated
- [x] Come back to visualizations to show what the sum stats mean
- [x] Embrace the site by species matrix- switch to hillR
- [x] Add plots of metrics
- [x] Incorporate more practice in the traits
- [x] redo variable names to match Renata's names
- [x] explain body size
- [x] Make it clear that we're just assigning average trait values to species 
- [x] read in the aggregated abundance data
- [x] Change Hill number section to hillR- don't make it a challenge- use pivot_wider()
- [x] Show histogram and density plot overlaid 
- [x] specify ylim and xlim in the plots
- [x] remove eval=FALSE
